import Head from "next/head";
import { getTodayPost } from "../lib/posts";
import STitle from "./components/STitle";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ titleData }) {
  return (
    <>
      <Head>
        <title>Random Titles</title>
        <meta
          name="description"
          content="Generated by create next app; A website for review infomation/news"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="Parent h-screen mx-20 my-5">
        <div className="grid gap-2 grid-cols-12">
          {/* <h1 className="text-3xl font-bold underline">HERO TITLE</h1> */}
          <div className="h-20 col-start-1 row-start-1"></div>
          <div className="h-20 col-start-1 row-start-2"></div>
          <div className="h-20 col-start-1 row-start-3"></div>
          <div className="h-20 col-start-1 row-start-4"></div>
          <div className="h-20 col-start-1 row-start-5"></div>
          <div className="col-start-2 row-start-3 col-span-2">
            <STitle {...titleData[0]} />
          </div>
          <div className="col-start-6 row-start-2 col-span-2">
            <STitle {...titleData[1]} />
          </div>
          <div className="col-start-9 row-start-4 col-span-2">
            <STitle {...titleData[2]} />
          </div>
        </div>
        <div className="mx-auto flex justify-center h-16 w-2/3 text-5xl font-light tracking-wider font-mono text-white hover:bg-sky-900 transition duration-500 ">
          Random Titles
        </div>
        <div className="grid gap-2 grid-cols-12">
          <div className="h-20 col-start-1 row-start-1"></div>
          <div className="h-20 col-start-1 row-start-2"></div>
          <div className="h-20 col-start-1 row-start-3"></div>
          <div className="h-20 col-start-1 row-start-4"></div>
          <div className="h-20 col-start-1 row-start-5"></div>
          <div className="col-start-3 row-start-1 col-span-2">
            <STitle {...titleData[3]} />
          </div>
          <div className="col-start-6 row-start-3 col-span-2">
            <STitle {...titleData[4]} />
          </div>
          <div className="col-start-10 row-start-2 col-span-2">
            <STitle {...titleData[5]} />
          </div>
        </div>
      </main>
    </>
  );
}

export function getStaticProps() {
  const titleData = getTodayPost();
  return {
    props: {
      titleData,
    },
  };
}
